Airbnb_itam/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :propiedades
  resources :usuarios


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Airbnb_itam/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Airbnb_itam/app/models/propiedad.rb
class Propiedad < ApplicationRecord
	has_and_belongs_to_many :usuarios
	belongs_to :usuario

end

Airbnb_itam/app/models/usuario.rb
class Usuario < ApplicationRecord
	has_and_belongs_to_many :propiedads
	has_many :propiedads
end

Airbnb_itam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Airbnb_itam/app/controllers/propiedades_controller.rb
class PropiedadesController < ApplicationController
	def index
		@propiedades = Propiedad.all
	end
	def show
		@propiedad = Propiedad.find(params[:id])
	end
	def create
		@propiedad = Propiedad.new(propiedad_params)
		@propiedad.save
		redirect_back fallback_location: { action: "index"}
	end
	private
  	def propiedad_params
    	params.require(:propiedad).permit(:descripcion, :calle, :num_ext, :num_int, :colonia, :cp, :delegacion, :precio, :tipo_habitacion, :wifi, :cable, :agua, :gas, :gas_natural, :telefono, :tipo_contrato, :usuario_id)
  	end
end

Airbnb_itam/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	def new
		@usuario= Usuario.new
		render "usuarios/new"
	end
	def create
		@usuario = Usuario.new(usuario_params)
		@usuario.save
		redirect_to @usuario
	end
	def show
		@usuario = Usuario.find(params[:id])
		@propiedades = Propiedad.where("usuario_id=?",params[:id])
		@propiedad = Propiedad.new
	end

private
  	def usuario_params
    	params.require(:usuario).permit(:nombre, :apellido, :email, :fecha_nac, :ubicacion, :telefono, :is_casero)
  	end
end

Airbnb_itam/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@propiedad = Propiedad.new
  end
  def create
  	render plain: params[:propiedad].inspect
  end	
end

Airbnb_itam/app/helpers/application_helper.rb
module ApplicationHelper
end

Airbnb_itam/app/helpers/inquilino_helper.rb
module InquilinoHelper
end

Airbnb_itam/app/helpers/profile_helper.rb
module ProfileHelper
end

Airbnb_itam/app/helpers/propiedades_helper.rb
module PropiedadesHelper
end

Airbnb_itam/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Airbnb_itam/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Airbnb_itam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbItam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Airbnb_itam/app/views/propiedades/index.html.erb
<!DOCTYPE html>
<html lang="en">
  
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Aquí van los botones de navegación y el AirBnB ITAM del lado derecho -->
                <!-- Deberíamos hacer un logo -->
                <div class="row">
                    <div class="col-md-5">
                        <h1>HabITAM</h1>
                    </div>
                    <div class="col-md-7" >
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            
                                <ul class="nav navbar-nav">
                                    <li>
                                        <a href=<%= url_for(action: 'index', controller: 'welcome') %>>
                                            Inicio
                                        </a>
                                    </li>
                                    <li>
                                        <a href="../usuarios/new.html"> Crear perfil</a>
                                    </li>
                                    <li>
                                        <a href="../propiedades/">Buscar</a>
                                    </li>
                                <!-- <li>
                                    <a href="contact.html">Contact</a>
                                </li> -->

                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <!-- <div>
            <h1 class="brand">Air BnB ITAM</h1>
        </div>
        <div class="address-bar">by Partido-ADSIon-Nacional</div>-->

        <!-- Navigation -->
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                    <a class="navbar-brand" href="index.html">HabITAM</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
               
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <div class="container" style="width: 90%;">

            <div class="col-md-3 text-center">
                <div class="row">
                    <div class="box">
                        <!-- Datos del usuario -->
                        <div class="row">
                          <div class="col-md-10 col-md-offset-1">
                            <hr>
                            <h3 id="nombre_usuario"> Filtros</h3>
                            <hr>

                            <h4> Tipo de habitación </h4>
                              <div class="row">
                                <%= label_tag(:tipo_habitacion, "Casa", :class => "col-md-7 text-right") %>
                                <%= check_box_tag :tipo_habitacion, :class => "col-md-3 col-md-offset-2" %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:tipo_habitacion, "Departamento", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:tipo_habitacion, :class => "col-md-3 col-md-offset-2") %> 
                              </div>
                        
                              <br>

                            <h4> Tipo de contrato </h4>
                              <div class="row">
                                <%= label_tag(:tipo_contrato, "Lugar completo", :class => "col-md-7 text-right") %>
                                <%= check_box_tag :tipo_contrato, :class => "col-md-3 col-md-offset-2" %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:tipo_contrato, "Compartido", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:tipo_contrato, :class => "col-md-3 col-md-offset-2") %> 
                              </div>
                        
                              <br>

                            <h4> Servicios</h4>
                              <div class="row">
                                <%= label_tag(:servicios, "Wi-Fi", :class => "col-md-7 text-right") %>
                                <%= check_box_tag :servicios, :class => "col-md-3 col-md-offset-2" %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:servicios, "Cable", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:servicios, :class => "col-md-3 col-md-offset-2") %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:servicios, "Agua", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:servicios, :class => "col-md-3 col-md-offset-2") %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:servicios, "Gas", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:servicios, :class => "col-md-3 col-md-offset-2") %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:servicios, "Gas natural", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:servicios, :class => "col-md-3 col-md-offset-2") %> 
                              </div>

                              <div class="row">
                                <%= label_tag(:servicios, "Telefono", :class => "col-md-7 text-right") %>
                                <%= check_box_tag(:servicios, :class => "col-md-3 col-md-offset-2") %> 
                              </div>
                        
                              <br>
                              <br>

                              <div class="col-lg-12">
                                <button type="submit" class="btn btn-primary">Actualizar resultados</button>
                              </div>

                          </div>
                        </div> 
                    </div>
                </div>
            </div>

            <div class="col-md-8 col-sm-offset-1">
                <div class="row">
                    <div class="box">
                        <div class="col-lg-12">
                            <!--<div class="row" style="margin-bottom: 4%;">
                                <div class="col-md-12">
                                <hr>
                                <h1 class="intro-text text-center">
                                    <strong>Resultados</strong>
                                </h1>
                                <hr>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href='#'> <!-- Aquí aparecerá un modal para mostrar más detalles de la casa 
                                    <div class="thumbnail">
                                        <img id="imagen_casa" src="/casa_ejemplo.png" width="150" height="150">
                                        <div id="info_casa" class="caption text-center">
                                            <h4>Colonia</h4>
                                            <p> Precio: $$$$$</p>
                                            <p> Casa/Depa/Compartido </p>  
                                        </div>
                                    </div> </a>
                                </div>

                                <!-- Estos modales se tienen que ir agregando con un método, no?
                                <div class="col-md-4">
                                    <a href='#'>
                                    <div class="thumbnail">
                                        <img src="/casa_ejemplo.png" width="150" height="150">
                                        <div class="caption text-center">
                                            <h4>Colonia</h4>
                                            <p> Precio: $$$$$</p>
                                            <p> Casa/Depa/Compartido </p> 
                                        </div>
                                    </div> </a>
                                </div>
                                <div class="col-md-4">
                                    <a href='#'>
                                    <div class="thumbnail">
                                        <img src="/casa_ejemplo.png" width="150" height="150">
                                        <div class="caption text-center">
                                            <h4>Colonia</h4>
                                            <p> Precio: $$$$$</p>
                                            <p> Casa/Depa/Compartido </p>  
                                        </div>
                                    </div> </a>
                                </div>
                                <div class="col-md-4">
                                    <a href='#'>
                                    <div class="thumbnail">
                                        <img src="/casa_ejemplo.png" width="150" height="150">
                                        <div class="caption text-center">
                                            <h4>Colonia</h4>
                                            <p> Precio: $$$$$</p>
                                            <p> Casa/Depa/Compartido </p> 
                                        </div>
                                    </div> </a>
                                </div>
                                <div class="col-md-4">
                                    <a href='#'>
                                    <div class="thumbnail">
                                        <img src="/casa_ejemplo.png" width="150" height="150">
                                        <div class="caption text-center">
                                            <h4>Colonia</h4>
                                            <p> Precio: $$$$$</p>
                                            <p> Casa/Depa/Compartido </p> 
                                        </div>
                                    </div> </a>
                                </div>
                                 --> 
                               <% @propiedades.each do |propiedad| %>
                                <div class="col-md-4">
                                    <a href=<%url_for("/propiedades/#{@propiedad.id}") %>> <!-- Aquí aparecerá un modal para mostrar más detalles de la casa -->
                                    <div class="thumbnail">
                                        <img id="imagen_casa" src="/casa_ejemplo.png" width="150" height="150">
                                        <div id="info_casa" class="caption text-center">
                                            <h4>Colonia: <%= propiedad.colonia %></h4>
                                            <p> Precio:<%=propiedad.precio %></p>
                                            <p> <%= propiedad.tipo_habitacion %> </p>
                                            <p> <%= propiedad.tipo_contrato %> </p>    
                                        </div>
                                    </div> </a>
                                </div>
                            <%end%>


                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <p>Copyright &copy; Partido-ADSIon-Nacional</p>
                    </div>
                </div>
            </div>
        </footer>

    </body>

<html>

<!--<h1>Listado de propiedades </h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @propiedades.each do |propiedad| %>
    <tr>
   	 
      <td><%= propiedad.title %></td>
      <td><%= propiedad.calle %></td>
      <td><%= propiedad.colonia %></td>
      <td><%= propiedad.precio %></td>
      <td><%= propiedad.tipo_habitacion %></td>
      <td><%= propiedad.wifi %></td>
      <td><%= propiedad.cable %></td>
      <td><%= propiedad.agua %></td>
      <td><%= propiedad.gas %></td>
      <td><%= propiedad.gas_natural %></td>
      <td><%= propiedad.telefono %></td>
      <td><%= propiedad.tipo_contrato %></td>
      <td><%= link_to 'Show', propiedad_path(propiedad) %></td>
    </tr>
  <% end %>
</table> -->

Airbnb_itam/app/views/propiedades/show.html.erb
<!DOCTYPE html>
<html lang="en">
  
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Aquí van los botones de navegación y el AirBnB ITAM del lado derecho -->
            <!-- Deberíamos hacer un logo -->
            <div class="row">
                <div class="col-md-5">
                    <h1>HabITAM</h1>
                </div>
                <div class="col-md-7" >
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href=<%= url_for(action: 'index', controller: 'welcome') %>>
                                        Inicio
                                    </a>
                                </li>
                                <li>
                                    <a href="../usuarios/new.html"> Crear perfil</a>
                                </li>
                                <li>
                                    <a href="../propiedades/">Buscar</a>
                                </li>
                            <!-- <li>
                                <a href="contact.html">Contact</a>
                            </li> -->

                            </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- <div>
        <h1 class="brand">Air BnB ITAM</h1>
    </div>
    <div class="address-bar">by Partido-ADSIon-Nacional</div>-->

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">HabITAM</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
           
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container" style="width: 90%;">

        <div class="col-md-12 text-center">
            <div class="row">
                <div class="box">
                    <!-- Datos del usuario -->
                    <div class="row">
                    	<div class="col-md-12 text-center">
                    		<hr>
                    		<h3 id="nombre_usuario"> Detalles de la casa</h3>
                    		<hr>
                    	</div>
                    </div>
                    <div class="row">
                      <div class="col-md-4 col-md-offset-1 text-left">
                        
                        <p>
                        	<h3> $<%= @propiedad.precio %></h3>
                        </p>
                        <p>
                          <strong>Descripción: </strong>
                          <%= @propiedad.descripcion %>
                        </p>
                        

                        <p>
                        	<strong>Colonia: </strong>
                        	<%= @propiedad.colonia %>
                        </p>
                        

                        <p>
                         	<strong>Tipo de habitación:	</strong>
                        	<%= @propiedad.tipo_habitacion %>
                        </p>
                        

                        <p>
                        	<strong> Tipo de contrato: </strong>
                        	<%= @propiedad.tipo_contrato %>
                        </p>
                        

                        <p>
                        	<%= @propiedad.wifi %>
                        </p>
                        

                        <p>
                        	<%= @propiedad.cable %>
                        </p>
                        

                        <p>
                        	<%= @propiedad.agua %>
                        </p>
                        

                        <p>
                        	<%= @propiedad.gas %>
                        </p>
                        

                        <p>
                        	<%= @propiedad.gas_natural %>
                        </p>
                        

                      </div>
                      <div class="col-md-6">
                      	<div class="col-md-12 text-center">
                      	<br>
  	                        <div id="carousel-example-generic" class="carousel slide">
  	                            <!-- Indicators -->
  	                            <ol class="carousel-indicators hidden-xs">
  	                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
  	                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  	                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  	                            </ol>

  	                            <!-- Wrapper for slides -->
  	                            <div class="carousel-inner">
  	                                <div class="item active">
  	                                    <img class="img-responsive img-full" src="/recamara_departamento.jpg" alt="">
  	                                </div>
  	                                <div class="item">
  	                                    <img class="img-responsive img-full" src="/cocina_departamento.jpg" alt="">
  	                                </div>
  	                                <div class="item">
  	                                    <img class="img-responsive img-full" src="/sala_departamento.jpg" alt="">
  	                                </div>
  	                            </div>

  	                            <!-- Controls -->
  	                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
  	                                <span class="icon-prev"></span>
  	                            </a>
  	                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
  	                                <span class="icon-next"></span>
  	                            </a>
  	                        </div>
  	                    </div>
                      </div>                  
                    </div> 
                </div>
            </div>
        </div>
        <!-- <div class="col-md-7 col-sm-offset-1">
            <div class="row">
                <div class="box">
                    <div class="col-lg-12">

                        <!--<div class="row" style="margin-bottom: 4%;">
                            <div class="col-md-12">
                            <hr>
                            <h1 class="intro-text text-center">
                                <strong>Resultados</strong>
                            </h1>
                            <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <a href='#'> <!-- Aquí aparecerá un modal para mostrar más detalles de la casa 
                                <div class="thumbnail">
                                    <img id="imagen_casa" src="/casa_ejemplo.png" width="150" height="150">
                                    <div id="info_casa" class="caption text-center">
                                        <h4>Colonia</h4>
                                        <p> Precio: $$$$$</p>
                                        <p> Casa/Depa/Compartido </p>  
                                    </div>
                                </div> </a>
                            </div>

                            <!-- Estos modales se tienen que ir agregando con un método, no?
                            <div class="col-md-4">
                                <a href='#'>
                                <div class="thumbnail">
                                    <img src="/casa_ejemplo.png" width="150" height="150">
                                    <div class="caption text-center">
                                        <h4>Colonia</h4>
                                        <p> Precio: $$$$$</p>
                                        <p> Casa/Depa/Compartido </p> 
                                    </div>
                                </div> </a>
                            </div>
                            <div class="col-md-4">
                                <a href='#'>
                                <div class="thumbnail">
                                    <img src="/casa_ejemplo.png" width="150" height="150">
                                    <div class="caption text-center">
                                        <h4>Colonia</h4>
                                        <p> Precio: $$$$$</p>
                                        <p> Casa/Depa/Compartido </p>  
                                    </div>
                                </div> </a>
                            </div>
                            <div class="col-md-4">
                                <a href='#'>
                                <div class="thumbnail">
                                    <img src="/casa_ejemplo.png" width="150" height="150">
                                    <div class="caption text-center">
                                        <h4>Colonia</h4>
                                        <p> Precio: $$$$$</p>
                                        <p> Casa/Depa/Compartido </p> 
                                    </div>
                                </div> </a>
                            </div>
                            <div class="col-md-4">
                                <a href='#'>
                                <div class="thumbnail">
                                    <img src="/casa_ejemplo.png" width="150" height="150">
                                    <div class="caption text-center">
                                        <h4>Colonia</h4>
                                        <p> Precio: $$$$$</p>
                                        <p> Casa/Depa/Compartido </p> 
                                    </div>
                                </div> </a>
                            </div>
                             

                        </div> 
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Partido-ADSIon-Nacional</p>
                </div>
            </div>
        </div>
    </footer>

</body>

<html>

Airbnb_itam/app/views/usuarios/index.html.erb
<h1>Listado de usuarios </h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @usuarios.each do |usuario| %>
    <tr>
   	 
      <td><%= usuario.nombre %></td>
      <td><%= usuario.apellido %></td>
      <td><%= usuario.email %></td>
      <td><%= usuario.fecha_nac %></td>
      <td><%= usuario.ubicacion %></td>
      <td><%= usuario.telefono %></td>
      <td><%= usuario.is_casero %></td>
      <td><%= link_to 'Show', usuarios_path(usuarios) %></td>
    </tr>
  <% end %>
</table>